"""
Django settings for converse project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from os.path import join
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", '').split()
SITE_ID = 1


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_comments',
    'django_htmx',
    'django_social_share',
    'tailwind',
    'theme',
    'pwa',
    'crispy_forms',
    'crispy_bootstrap4',
    'social_django',
    'django_extensions',
    'taggit',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.postgres',
    'notify',
    'postman',
    'hitcount',
    'prose',
    'homepage',
    'users',
    'actions',
    'newss',
    'business',
    'crimes',
    'entertainments',
    'internationals',
    'sciences',
    'educations',
    'sports',
    'health_articles',
    'political_articles',
    'happening',
    'innovations',
    'lifestyles',
    'religions',
    'sport_articles',
    'cultures',
    'foods',
    'business__articles',
    'howtos',
    'celeb',
    'loves',
    'campuss',
    'personalitys',
    'events',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'converse.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'converse.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Etc/GMT-1'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

CSRF_TRUSTED_ORIGINS = ["http://localhost:1337"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CRISPY_ALLOWED_TEMPLATE_PACK = "bootstrap4"
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#redis connection
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

REDIS_URL = 'redis://cache:6379'
CHANNEL_LAYERS={
    "default":{
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG":{
            "hosts": REDIS_URL,
            },
           },
           }

AUTH_USER_MODEL = 'users.CustomUser'

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.core.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
)

#LOGIN_REDIRECT_URL = 'homepage'
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'

#Carnonical view of users
ABSOLUTE_URL_OVERRIDES = {
       'CustomUser': lambda u: reverse_lazy('Author_Profile_View',
        args=[u.id])
    }


 
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_HOST_USER = 'conversenigeria24@gmail.com' 
EMAIL_HOST_PASSWORD = 'zcpl xcqu plho fzvy ' 
EMAIL_PORT = 587 
EMAIL_USE_TLS = True

AUTHENTICATION_BACKENDS = [
'django.contrib.auth.backends.ModelBackend',
'users.authentication.EmailAuthBackend',
'social_core.backends.facebook.FacebookOAuth2',
'social_core.backends.twitter.TwitterOAuth',
'social_core.backends.google.GoogleOAuth2',

]


SOCIAL_AUTH_PIPELINE = [
'social_core.pipeline.social_auth.social_details',
'social_core.pipeline.social_auth.social_uid',
'social_core.pipeline.social_auth.auth_allowed',
'social_core.pipeline.social_auth.social_user',
'social_core.pipeline.user.get_username',
'social_core.pipeline.user.create_user',
'users.authentication.create_profile',
'social_core.pipeline.social_auth.associate_user',
'social_core.pipeline.social_auth.load_extra_data',
'social_core.pipeline.user.user_details',
]

SOCIAL_AUTH_PIPELINE+=('<users.authentication>.save_profile')

SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get("SOCIAL_AUTH_FACEBOOK_KEY")
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get("SOCIAL_AUTH_FACEBOOK_SECRET")
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']


SOCIAL_AUTH_TWITTER_KEY = os.environ.get("SOCIAL_AUTH_TWITTER_KEY")
SOCIAL_AUTH_TWITTER_SECRET = os.environ.get("SOCIAL_AUTH_TWITTER_SECRET")


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET")

TAILWIND_APP_NAME='theme'
INTERNAL_IPS=["127.0.0.1"]
NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd" 



PWA_APP_NAME = 'Converse'
PWA_APP_DESCRIPTION = 'We do it in group'
PWA_APP_THEME_COLOR = '#000000'
PWA_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ORIENTATION = 'any'
PWA_APP_ICONS = [
    {
				"src": "/static/pwa/images/icons/converse.jpg",
				"type": "image/jpg",
				"sizes": "72x72"
			}
]

PWA_APP_ICONS_APPLE = [
    {
       "src": "/static/pwa/images/icons/converse.jpg",
		"type": "image/jpg",
		"sizes": "212x128"
    }
]

PWA_SPLASH_SCREEN = [
    {
               "src": "/static/pwa/images/icons/converse.jpg",
				"type": "image/jpg",
				"sizes": "212x128",
                "media": '(device-width:320px) and (device-height:568px) and (-webkit-device-pixel-ratio:2)'
    }
]

PWA_APP_SHORTCUTS = [
    {
        'name': 'shortcut',
        'url': '/target',
        
    }
]

PWA_APP_SCREENSHOTS = [
    {
        'src':"/static/pwa/images/icons/converse.jpg",
		"type": "image/jpg",
		"sizes": "212x128",
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

NOTIFY_UPDATE_TIME_INTERVAL = (5000)

POSTMAN_AUTO_MODERATE_AS=True
POSTMAN_QUICKREPLY_QUOTE_BODY = True

